name: Deploy
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Setup .NET Core
      uses: actions/checkout@v2
      with:
        dotnet-version: 7.0.14

    - name: Install dependencies
      uses: actions/setup-dotnet@v1

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o '${{ github.workspace }}/out'

    - name: Zip Package
      run: |
        cd ${{ github.workspace }}/out
        zip -r ${{ github.workspace }}/out.zip *

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: backend
        environment_name: backend-dev
        region: sa-east-1
        version_label: ${{ github.run_id }}
        version_description:: ${{ github.sha }}
        deployment_package: ${{ github.workspace }}/out.zip
